### ISSUE TITLE
Integration of ebean-elastic in Play 2.5

### ISSUE THREAD

**Issue by felixqk** [ebean-orm/ebean-elastic#20]
Hi, Sir,

I am new to ebean and elastic search, I currently run an application using ebean + play + postgresql, I tried to add elastic search on top of my current stack. 

I followed the instruction here http://ebean-orm.github.io/docs/features/elasticsearch/get-started#SBT1

1. added dependency to built.sbt
  
`    libraryDependencies += "org.avaje.ebean" % "ebean-elastic" % "${version}"

2. Added @DocStore to my model class

```
@DocStore
@Entity
@Table(name="contact")
public class Contact {
...
}
```

However I found I still didn't figure out how to use it.

1. I didn't see any index mapping files generated, didin't find resources folder.
2. I didn't see properties file generated, which should contain the configuration for elastic search like followings

```
ebean.docstore.url=http://127.0.0.1:9200
ebean.docstore.active=true
ebean.docstore.generateMapping=true
ebean.docstore.dropCreate=true
#ebean.docstore.create=true
```

3. I couldn't use .setUseDocStore(true) like

_Contact.find().setUseDocStore(true)_ 

in my controller package, is there any package should I import?

Could you help to identify where goes wrong? what is the correct way of integrating in play for ebean-elastic?

Thanks!

Felix

**Comment by rbygrave** [comment]
How about starting with the example at: https://github.com/ebean-orm-examples/example-elastic ... and try and get that working first?

**Comment by rbygrave** [comment]
Note that with the Ebean project we have a policy of wanting questions to be sent to the forum rather than logged as github issues.

This policy is explained at http://ebean-orm.github.io/support

Cheers, Rob.

**Comment by rbygrave** [comment]
Closing ...
